language: groovy
sudo: false
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.grails"
jdk:
- openjdk8
services:
- memcached
- redis-server
before_install: "./install-sdkman.sh"
install: true
script: "./test-app.sh"
after_success: "./doc.sh"
env:
  global:
  - secure: i+HYyyMe2qXPZkP113Vo+uXDzWeiS96dE8EiURxB75HDLuQ1UuIKkfZylNyWXcJHh8gy6ypKffxjZ0FeN44FQeiChE+WC20Xh9UOG076zHogFIE/IooFawau+jcvqJzQU+3koDO9zocu8HfULqenfapSKri/5vMxaPTj85VdFfk=
  - secure: XBD/lDc+U/9c6qKKRKuhjxrMe8nIz6T3MtAgPr77bowh0c4EpZiIOQ5+dpUBvA6jL5h8UYck8DAeqC9H7RTG0ZQS+2eJQiEVQXTKfwfe53LQP1CUfAC94o4yNnIpZ9nRikbHKUIqIqla8PXl94TteSpbO9fhb6byFyiGFgGwi34=
  - secure: gb4ezV+KeMtpWVKoReJnK/6IEhCvnp+NLo9Q7NrxL7kdBch8zqHmY8ToG/MW8faDEG2JCp4XzIh+0Sh/kzkQY1KurI53M92TNjhXO0BTp/mUiToMhHEEkedZ99p+aCCSHoGzZiwLAOAuvcp7swQ6N75u6smrCBSy/gZVkXSVBnk=
  - GIT_NAME="Alvaro Sanchez-Mariscal"
  - GIT_EMAIL="alvaro.sanchezmariscal@gmail.com"
before_deploy: "./publish-plugin.sh"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: QpD/nt7wNuLHntXz2+C0LeD/W1m1F8x84t7KbFjNg+lswa3tfq7CZE4w979JUt0BQKJWR4mKb61ENtJtsVey/gth8tpO65xMLdDZ0+eYJ+oN9lCMfnzNfMOi7NWAixHeKe6bfClvW7xU8LsfY3eMZKiRPJ1SBNJ26b9YtkptTTU=
  file: spring-security-rest/build/libs/spring-security-rest-${TRAVIS_TAG}.jar
  on:
    repo: alvarosanchez/grails-spring-security-rest
    tags: true
